dist: xenial
language: python
cache: pip
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"
matrix:
    allow_failures:
        - python: "nightly"
install:
    - pip install pipenv --upgrade-strategy=only-if-needed
    - pipenv install --dev
script:
    - bash scripts/test.sh
after_script:
    - bash <(curl -s https://codecov.io/bash)
